Code_core/ProjectManagement/urls.py
from django.urls import path
from ProjectManagement import views

app_name = 'ProjectManagement'
urlpatterns = [
    #Lv0 App
    path('', views.login, name='login'),
    #Lv1 User 
    path('<int:user_id>/index',views.index, name='index'), 
    path('<int:user_id>/projectoverview',views.projectoverview, name='projectoverview'),
    path('<int:user_id>/activity',views.activity, name='activity'),
    path('<int:user_id>/gantt',views.gantt, name='gantt'),
    # path('projects',views.projects, name='projects'),
    path('<int:user_id>/newproject',views.newproject, name='newproject'),  

    #Lv2 User/Project
    path('<int:user_id>/<int:project_id>/',views.projects, name='projects'),
    path('<int:user_id>/<int:project_id>/editproject',views.editproject, name='editproject'), 
    path('<int:user_id>/<int:project_id>/<int:task_id>/',views.tasks,name='tasks'),
    path('<int:user_id>/<int:project_id>/<int:task_id>/edittask',views.edittask, name='edittask'), 
    path('<int:user_id>/<int:project_id>/newtask',views.newtask, name='newtask'), 
    path('<int:user_id>/<int:project_id>/adduser',views.adduser, name='adduser'), 

    #Lv3 User/Project/Task
    path('<int:user_id>/<int:project_id>/<int:task_id>/newphase',views.newphase, name='newphase'), 
    
    #Lv4 User/Project/Task/Phase
    path('<int:user_id>/news',views.news, name='news'), 
    path('login',views.login, name='login'), 
    path('<int:user_id>/support',views.support, name='support'),  
    path('forgot_password',views.forgot_password, name='forgot_password'), 
]

Code_core/ProjectManagement/templates/adduser.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>VPBS Project Management </title>

    <!-- Bootstrap -->
    <link href="{% static 'ProjectManagement/vendors/bootstrap/dist/css/bootstrap.min.css '%}'" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'ProjectManagement/vendors/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'ProjectManagement/vendors/nprogress/nprogress.css'%}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'ProjectManagement/vendors/iCheck/skins/flat/green.css'%}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'ProjectManagement/build/css/custom.min.css'%}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container ">
      <div class="">
        

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav style="display: inline;">
              
              <ul class="nav navbar-nav navbar-left" >
                  <li><a href="{% url 'ProjectManagement:index' %}"><i class="fa fa-home "></i> Overview </a></li>
                  <li><a href="{% url 'ProjectManagement:activity' %}"><i class="fa fa-paw "></i> Activities </a></li>
                  <li><a href="{% url 'ProjectManagement:gantt' %}"><i class="fa fa-bar-chart "></i> Gantt </a></li>
                  <li><a href="{% url 'ProjectManagement:projectoverview' %}"><i class="fa fa-bullseye "></i> Project </a></li>
                  <li><a href="{% url 'ProjectManagement:news' %}"><i class="fa fa-newspaper-o "></i> News </a></li>
                  <li><a href="{% url 'ProjectManagement:support' %}"><i class="fa fa-support "></i> Support </a></li>
<!--               </ul>

              <ul class="nav navbar-nav navbar-right" >      -->
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="">Hoàng hihi
                    <span class=" fa fa-angle-down"></span>
                  </a>
                        <ul class="dropdown-menu dropdown-usermenu dropdown-menu-right pull-right">
                          <li><a href="javascript:;"> Profile</a></li>
                          <li>
                            <a href="javascript:;">
                              <span class="badge bg-red pull-right">50%</span>
                              <span>Settings</span>
                            </a>
                          </li>
                          <li><a href="javascript:;">Help</a></li>
                          <li><a href="{% url 'ProjectManagement:login'%}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                        </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
                
              </ul>
              

            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Add new member</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Project <small>Project Name </small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">



                      <div class="form-group" >
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"> Member Id <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                      </div>
                      
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3" style="padding-left: 200px">
                          <button type="submit" class="btn btn-success">Add Member</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <<!-- footer>
          <div class="pull-right">
            VPBS Project Management - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer> -->
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'ProjectManagement/vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'ProjectManagement/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'ProjectManagement/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'ProjectManagement/vendors/nprogress/nprogress.js' %}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{% static 'ProjectManagement/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'ProjectManagement/vendors/iCheck/icheck.min.js' %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static 'ProjectManagement/vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    <!-- bootstrap-wysiwyg -->
    <script src="{% static 'ProjectManagement/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/jquery.hotkeys/jquery.hotkeys.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/google-code-prettify/src/prettify.js' %}"></script>
    <!-- jQuery Tags Input -->
    <script src="{% static 'ProjectManagement/vendors/jquery.tagsinput/src/jquery.tagsinput.js' %}"></script>
    <!-- Switchery -->
    <script src="{% static 'ProjectManagement/vendors/switchery/dist/switchery.min.js' %}"></script>
    <!-- Select2 -->
    <script src="{% static 'ProjectManagement/vendors/select2/dist/js/select2.full.min.js' %}"></script>
    <!-- Parsley -->
    <script src="{% static 'ProjectManagement/vendors/parsleyjs/dist/parsley.min.js' %}"></script>
    <!-- Autosize -->
    <script src="{% static 'ProjectManagement/vendors/autosize/dist/autosize.min.js' %}"></script>
    <!-- jQuery autocomplete -->
    <script src="{% static 'ProjectManagement/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js' %}"></script>
    <!-- starrr -->
    <script src="{% static 'ProjectManagement/vendors/starrr/dist/starrr.js' %}"></script>
    <!-- Custom Theme Scripts -->
    <script src="{% static 'ProjectManagement/build/js/custom.min.js' %}"></script>
	
  </body>
</html>

Code_core/ProjectManagement/templates/forgot_password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>VPBS Project Management | </title>

    <!-- Bootstrap -->
    <link href="{% static 'ProjectManagement/vendors/bootstrap/dist/css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'ProjectManagement/vendors/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'ProjectManagement/vendors/nprogress/nprogress.css'%}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static 'ProjectManagement/vendors/animate.css/animate.min.css'%}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'ProjectManagement/build/css/custom.min.css'%}" rel="stylesheet">
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form>
              <h1>Take your password</h1>
              <div>
                <input type="text" class="form-control" placeholder="Username" required="" />
              </div>
              <div>
                <input type="email" class="form-control" placeholder="Email" required="" />
              </div>
              <div>
                <a class="btn btn-default submit" href="{% url 'ProjectManagement:login' %}">Take</a>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
<!--                 <p class="change_link">Already take your password back ?
                  <a href="login.html" class="to_register"> Log in </a>
                </p> -->

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="fa fa-bank"></i> VPBS Project Management</h1>
                  <p>©2016 All Rights Reserved. VPBS Project Management is a Bootstrap 3 template. Privacy and Terms</p>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
  </body>
</html>
  

Code_core/ProjectManagement/templates/gantt.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>VPBS Project Management </title>

    <!-- Bootstrap -->
    <link href="{% static 'ProjectManagement/vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'ProjectManagement/vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'ProjectManagement/vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'ProjectManagement/vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
	
    <!-- bootstrap-progressbar -->
    <link href="{% static 'ProjectManagement/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'ProjectManagement/vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'ProjectManagement/vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'ProjectManagement/build/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container ">
      <div class="">
        

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav style="display: inline;">
              
              <ul class="nav navbar-nav navbar-left" >
                <li><a href="{% url 'ProjectManagement:index' %}"><i class="fa fa-home "></i> Overview </a></li>
                <li><a href="{% url 'ProjectManagement:activity' %}"><i class="fa fa-paw "></i> Activities </a></li>
                <li><a href="{% url 'ProjectManagement:gantt' %}"><i class="fa fa-bar-chart "></i> Gantt </a></li>
                <li><a href="{% url 'ProjectManagement:projectoverview' %}"><i class="fa fa-bullseye "></i> Project </a></li>
                <li><a href="{% url 'ProjectManagement:news' %}"><i class="fa fa-newspaper-o "></i> News </a></li>
                <li><a href="{% url 'ProjectManagement:support' %}"><i class="fa fa-support "></i> Support </a></li>
<!--               </ul>

              <ul class="nav navbar-nav navbar-right" >      -->
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="">Hoàng hihi
                    <span class=" fa fa-angle-down"></span>
                  </a>
                        <ul class="dropdown-menu dropdown-usermenu dropdown-menu-right pull-right">
                          <li><a href="javascript:;"> Profile</a></li>
                          <li>
                            <a href="javascript:;">
                              <span class="badge bg-red pull-right">50%</span>
                              <span>Settings</span>
                            </a>
                          </li>
                          <li><a href="javascript:;">Help</a></li>
                          <li><a href="% url 'ProjectManagement:login' %"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                        </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="{% static 'ProjectManagement/images/img.jpg' %}" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
                
              </ul>
              

            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <!-- top tiles -->
          
          <!-- /top tiles -->

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="dashboard_graph">

                <div class="row x_title">
                  <div class="col-md-6">
                    <h3> Gantt chart: <i><small> Task Scheduling </small></i> 
                      <a href="{% url 'ProjectManagement:editproject'%}"><button type="button" class="btn btn-link" >Edit</button> </a>
                    </h3>
                  </div>
                  <div class="col-md-6">
                    <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                      <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                      <span>December 30, 2014 - January 28, 2015</span> <b class="caret"></b>
                    </div>
                  </div>
                </div>

                <div class="col-md-9 col-sm-9 col-xs-12">
                  <div id="chart_plot_01" class="demo-placeholder"></div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12 bg-white">
                  <div class="x_title">
                    <h2>Project Infomation</h2>
                    <div class="clearfix"></div>
                  </div>

                  <div class="col-md-12 col-sm-12 col-xs-6">
                    <div>
                      <p style="font-size: 16px" >Project Status &emsp;&emsp;&emsp;&emsp; <button type="button" class="btn btn-danger btn-xs">Warning</button> </p> 
                    </div>
                    <div>
                      <p style="font-size: 16px "> Done: &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;60%
                          <div class="progress progress_sm" style="width: 95%;">
                            <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="60"> </div>
                          </div>
                      </p> 
                    </div>
                    <div>
                      <p style="font-size: 16px "> Due Date:  &emsp;&emsp;&emsp;&emsp;12/09/2018 </p> 
                    </div>
                  </div>
                  <div class="col-md-12 col-sm-12 col-xs-6">
                    <div>
                      <p style="font-size: 16px "> Due Date:  &emsp;&emsp;&emsp;&emsp;02/12/2018 </p> 
                    </div>
                    <div>
                      <p style="font-size: 16px "> Description:</p> 
                      <div>Đây là phần mô tả của dự án ạ
                           mong là phần front-end hoạt động tốt. 
                           Description đến đây là hết 
                      </div>
                    </div>
                  </div>

                </div>

                <div class="clearfix"></div>
              </div>
            </div>

          </div>
          <br />


         


                    <!-- start project list -->
                  <!-- <ul class="nav child_menu"> -->
                    
            

          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
  <!--       <footer>
          <div class="pull-right">
            VPBS Project Management - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer> -->
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'ProjectManagement/vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'ProjectManagement/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'ProjectManagement/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'ProjectManagement/vendors/nprogress/nprogress.js' %}"></script>
    <!-- Chart.js -->
    <script src="{% static 'ProjectManagement/vendors/Chart.js/dist/Chart.min.js' %}"></script>
    <!-- gauge.js -->
    <script src="{% static 'ProjectManagement/vendors/gauge.js/dist/gauge.min.js' %}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{% static 'ProjectManagement/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'ProjectManagement/vendors/iCheck/icheck.min.js' %}"></script>
    <!-- Skycons -->
    <script src="{% static 'ProjectManagement/vendors/skycons/skycons.js' %}"></script>
    <!-- Flot -->
    <script src="{% static 'ProjectManagement/vendors/Flot/jquery.flot.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/Flot/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/Flot/jquery.flot.time.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/Flot/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/Flot/jquery.flot.resize.js' %}"></script>
    <!-- Flot plugins -->
    <script src="{% static 'ProjectManagement/vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/flot.curvedlines/curvedLines.js' %}"></script>
    <!-- DateJS -->
    <script src="{% static 'ProjectManagement/vendors/DateJS/build/date.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'ProjectManagement/vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static 'ProjectManagement/vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'ProjectManagement/vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'ProjectManagement/build/js/custom.min.js' %}"></script>
  
  </body>
</html>